language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
env:
  - NSQ_DOWNLOAD=nsq-0.3.8.linux-amd64.go1.6.2 GOARCH=amd64
  - NSQ_DOWNLOAD=nsq-0.3.8.linux-amd64.go1.6.2 GOARCH=386
  - NSQ_DOWNLOAD=nsq-1.0.0-compat.linux-amd64.go1.8 GOARCH=amd64
  - NSQ_DOWNLOAD=nsq-1.0.0-compat.linux-amd64.go1.8 GOARCH=386
  - NSQ_DOWNLOAD=nsq-1.1.0.linux-amd64.go1.10.3 GOARCH=amd64
  - NSQ_DOWNLOAD=nsq-1.1.0.linux-amd64.go1.10.3 GOARCH=386
script:
  - ./travis.sh
notifications:
  email: false
sudo: false
